export const ACTION_TYPE = {
  SET_DOCTOR_DATA: 'SET_DOCTOR_DATA',
  SET_DOCTORS_DATA: 'SET_DOCTORS_DATA',
  UPDATE_DOCTORS_DATA: 'UPDATE_DOCTORS_DATA',
  UPDATE_DOCTOR_DATA: 'UPDATE_DOCTOR_DATA',
  DELETE_DOCTOR_DATA: 'DELETE_DOCTOR_DATA',
  UPDATE_SPECIALIST_DATA: 'UPDATE_SPECIALIST_DATA',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_SPECIALIST_DATA: 'SET_SPECIALIST_DATA',
  DEL_SPECIALIST_DATA: 'DEL_SPECIALIST_DATA',
  LOGOUT: 'LOGOUT',
};
